const PRODUCTS = [
  {
    id: "p1",
    name: "Sofa Minimalis Sven 3-Dudukan",
    category: "living-room",
    categoryLabel: "Ruang Tamu",
    price: 8499000,
    rating: 4.8,
    reviews: 124,
    image: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=800&q=80",
    description: "Sofa Sven menggabungkan estetika Nordik yang bersih dengan kenyamanan luar biasa. Rangka kayu solid yang kuat dibalut dengan kain tenun premium abu-abu hangat. Bantalannya menggunakan busa kepadatan tinggi dengan lapisan bulu angsa sintetis untuk kelembutan ekstra.",
    dimensions: "210 cm x 88 cm x 82 cm (PxLxT)",
    material: "Kayu Oak Solid, Kain Tenun Linen Premium, Busa Densitas Tinggi",
    inStock: true
  },
  {
    id: "p2",
    name: "Kursi Lengan Bouclé Astrid",
    category: "living-room",
    categoryLabel: "Ruang Tamu",
    price: 3799000,
    rating: 4.9,
    reviews: 86,
    image: "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=800&q=80",
    description: "Kursi lengan Astrid menghadirkan keanggunan modern ke sudut ruangan Anda. Dibungkus dengan kain bouclé yang lembut dan bertekstur mewah, kursi ini memiliki bentuk melengkung organik yang memeluk tubuh dengan nyaman. Kaki besi hitam matte memberikan aksen kontras yang kokoh.",
    dimensions: "85 cm x 80 cm x 78 cm (PxLxT)",
    material: "Kain Bouclé Premium, Rangka Baja, Kaki Powder Coated Black",
    inStock: true
  },
  {
    id: "p3",
    name: "Meja Kopi Kayu Jati Milo",
    category: "living-room",
    categoryLabel: "Ruang Tamu",
    price: 2499000,
    rating: 4.7,
    reviews: 62,
    image: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=800&q=80",
    description: "Meja kopi Milo memancarkan keindahan alami kayu jati pilihan. Dengan bentuk bulat yang ramah dan kaki meruncing khas mid-century modern, meja ini memiliki rak bawah tambahan untuk menyimpan majalah atau remote control Anda.",
    dimensions: "80 cm (Diameter) x 42 cm (Tinggi)",
    material: "Kayu Jati Solid, Finishing Natural Oil",
    inStock: true
  },
  {
    id: "p4",
    name: "Meja Makan Oak Solid Freya",
    category: "dining-room",
    categoryLabel: "Ruang Makan",
    price: 6899000,
    rating: 4.9,
    reviews: 43,
    image: "https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=800&q=80",
    description: "Freya adalah meja makan dengan desain minimalis namun berkarakter kuat. Dibuat sepenuhnya dari kayu oak putih Eropa pilihan, meja ini menampilkan keindahan serat kayu alami dengan sentuhan akhir matte lacquer yang tahan gores dan mudah dibersihkan.",
    dimensions: "180 cm x 90 cm x 75 cm (PxLxT) - Muat hingga 6 orang",
    material: "Kayu Oak Putih Solid, Matte Polyurethane Finish",
    inStock: true
  },
  {
    id: "p5",
    name: "Kursi Makan Kayu Nora",
    category: "dining-room",
    categoryLabel: "Ruang Makan",
    price: 1499000,
    rating: 4.6,
    reviews: 95,
    image: "https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=800&q=80",
    description: "Kursi makan Nora menawarkan kenyamanan duduk yang ergonomis dengan siluet klasik yang tak lekang oleh waktu. Bagian sandaran punggung yang melengkung memberikan topangan optimal, sementara dudukan berlapis busa tipis dengan kain tenun memberikan kelembutan ekstra.",
    dimensions: "48 cm x 52 cm x 80 cm (PxLxT)",
    material: "Kayu Ash Solid, Kain Tenun Wol, Dudukan Busa",
    inStock: true
  },
  {
    id: "p6",
    name: "Tempat Tidur Minimalis Ran Frame",
    category: "bedroom",
    categoryLabel: "Kamar Tidur",
    price: 9299000,
    rating: 4.8,
    reviews: 78,
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80",
    description: "Rangka tempat tidur Ran menghadirkan ketenangan ala resort Skandinavia ke kamar tidur Anda. Rangka kayunya yang rendah memberikan kesan ruangan yang lebih lapang, dengan sandaran kepala (headboard) berdesain kisi-kisi kayu yang anggun.",
    dimensions: "212 cm x 186 cm x 100 cm (PxLxT) - Untuk Kasur King Size (180x200)",
    material: "Kayu Oak Solid, Lapisan Veneer Oak Premium",
    inStock: true
  },
  {
    id: "p7",
    name: "Meja Samping Tempat Tidur Arlo",
    category: "bedroom",
    categoryLabel: "Kamar Tidur",
    price: 1849000,
    rating: 4.7,
    reviews: 51,
    image: "https://images.unsplash.com/photo-1532372320978-9b4d8a3a8245?auto=format&fit=crop&w=800&q=80",
    description: "Meja samping Arlo menggabungkan fungsionalitas dan keindahan visual. Dilengkapi dengan satu laci tarik ber-glide mulus untuk menyimpan barang pribadi Anda, serta ruang terbuka di bagian bawah untuk menumpuk buku favorit Anda sebelum tidur.",
    dimensions: "45 cm x 40 cm x 55 cm (PxLxT)",
    material: "Kayu Jati Solid, Rel Laci Stainless Steel",
    inStock: true
  },
  {
    id: "p8",
    name: "Meja Kerja Ergonomis Hugo",
    category: "workspace",
    categoryLabel: "Ruang Kerja",
    price: 4199000,
    rating: 4.9,
    reviews: 39,
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80",
    description: "Meja kerja Hugo dirancang khusus untuk meningkatkan produktivitas dan fokus Anda di rumah. Area meja yang luas memberikan ruang cukup untuk setup laptop/monitor ganda, sedangkan dua laci ramping tersembunyi membantu menjaga meja tetap rapi bebas kabel berserakan.",
    dimensions: "130 cm x 60 cm x 75 cm (PxLxT)",
    material: "Kayu Walnut Solid, Kaki Besi Powder Coated Matte",
    inStock: true
  },
  {
    id: "p9",
    name: "Kursi Kantor Kulit Kellan",
    category: "workspace",
    categoryLabel: "Ruang Kerja",
    price: 3299000,
    rating: 4.8,
    reviews: 47,
    image: "https://images.unsplash.com/photo-1580481072645-022f9a6dbf27?auto=format&fit=crop&w=800&q=80",
    description: "Kursi kantor Kellan memadukan kenyamanan ergonomis kursi kerja modern dengan estetika eksekutif yang mewah. Dilapisi kulit vegan premium berwarna cokelat karamel yang berpori, kursi ini dilengkapi sandaran tangan kayu jati dan mekanisme kemiringan sinkron yang dapat dikunci.",
    dimensions: "65 cm x 65 cm x 115-125 cm (Adjustable)",
    material: "Kulit Vegan Premium, Sandaran Tangan Kayu Jati, Kaki Aluminium Cor",
    inStock: true
  }
];
